### ISSUE TITLE
Crash at startup when using Thaumic Augmentation

### ISSUE THREAD

**Issue by Null-151** [jbredwards/Baubley-Elytra-Mod#4]
Just like the title says, this mod causes a crash if that mod is present
Crashlog: https://mclo.gs/ZfhEyGd

**Comment by TheCodex6824** [comment]
Thaumic Augmentation dev here. This crash happens because my coremod looks for `getItemStackFromSlot` to insert instructions after, and you seem to delete it and replace it with a hook to your own code. Please don't delete code like that unless you have no other choice - it causes anything else (like TA) that also wants to inject code to have a hard time. Instead, I suggest you leave the original call in, but add a call to a static function that takes the result of `getItemStackFromSlot` and returns the new value that should be used.

**Comment by jbredwards** [comment]
fixed in v1.3.2
